### PR TITLE
spike for spring example

### PR DESCRIPTION
**Pull request by clojj**
Hi, and first kudos for adding these handlers (for Ktor) !

This may not yet be complete.. just to start somewhere with a spring example.
Obviously, the spring specifics will have to move to a new module "tribune-spring" (in the works).

So what do you think ?

At some point, when arrow-proofs (Kotlin must have a stable IR) is ready, I'd alos like to explore that route.
Plain Kotlin context receivers may be a valuable addition too, but I am still exploring that (that's why I left the compiler arg for it in the grable build)

### CODE REVIEW

**Comment by sksamuel** [comment]
I like it.

We should make the tribune-spring module you mentioned. Do you want me to merge this first ?

**Review by sksamuel — APPROVED** [review]

**Comment by clojj** [comment]
Hi, no merge yet.
I will fix some quirks and add the spring module first....

**Comment by clojj** [comment]
just commented my todo's in spring.kt

**Comment by sksamuel** [comment]
I don't see any todos ?

**Comment by clojj** [comment]
I used Github Mobile App and commented in source spring.kt, never mind..I
will commit later

Sam ***@***.***> schrieb am Mi., 24. Aug. 2022, 09:55:

**Comment by clojj** [comment]
:( @JsonUnwrapped doesn't seem to work with Kotlin, noooooo......!

**Comment by sksamuel** [comment]
What's json unwrapped do ?

**Comment by clojj** [comment]
It would not serialize a field of a complex type, instead it would just directly serialize the complex type

**Comment by clojj** [comment]
The good guys from arrow-kt have a Jackson lib, which covers several arrow types. So devs can use that, if they actually  want to return "wrapped" responses.

Ultimately, tribune-spring should be flexibel and offer ways to respond according to APIs needs

**Comment by sksamuel** [comment]
So essentially you were trying to create the spring version of my ktor "handler" ?

**Comment by clojj** [comment]
Almost.. your Handler ha unit return type, which is not possible with Spring RestController methods.

**Comment by clojj** [comment]
@sksamuel 
Issue with JsonUnwrapped resolved, I'll try to polish this PR soon,,,

**Comment by clojj** [comment]
Apart from being an example/teaser for spring folks, the basic question seems what real-world features such a handler can bring to the table: if it should serve as a generic "protection layer" in API controllers, return type and configurability stand out to me...

**Comment by clojj** [comment]
@sksamuel first shot at trubune-spring module

**Comment by sksamuel** [comment]
Would this return a 200 for both error and success?

**Comment by clojj** [comment]
> Would this return a 200 for both error and success?

no it should return 404

**Comment by clojj** [comment]
I am really struggling with gradle-multiplatform... weird messages in IntelliJ, restart fixes them, gives me the feeling of 'only works on my machine'

**Comment by clojj** [comment]
there probably is a better alternative to having nullable parameters for each parse-outcome, but hey.. it's Kotlin :)

**Comment by clojj** [comment]
got rid of that nullables + fixed response code

**Comment by clojj** [comment]
There should also probably be a reactive-spring example later, as we are preferrably in suspend land :)

**Comment by clojj** [comment]
@sksamuel 
I think this is could be ready for merge, what do you think ?

**Comment by sksamuel** [comment]
I'll check it out.

**Comment by sksamuel** [comment]
This is nice. Pity we need the wrapper json but otherwise slick.

**Comment by sksamuel** [comment]
Ok cool.

**Pull request merged**
