### PR TITLE
fix dependency directions and put parsers & opaque types together

### PR DESCRIPTION
**Pull request by clojj**
Hi, I cleaned up a little
for that I introduced an interface `BookInputData` serving as input-type to both book parser

btw, I borrowed the concept of 'opaque type' from Elm's Richard Feldman (make impossible states impossible, fits well with 'parse don't validate). Now our book parsers serve as save constructor functions.

### CODE REVIEW

**Comment by clojj** [comment]
oh my.. now Ktor won't print any output, because `withParsedInput` seems not to be executed suddenly.
Last time I had this, I could fix it by renaimg then .kt in `tribune-examples-model` module, but now.. I don't know.. something about multiplatform build I guess ?

**Comment by sksamuel** [comment]
I would just leave it as a class. The interface isn't making it clearer because in a real world app you wouldn't have both types of  class.

**Comment by clojj** [comment]
yep, makes little sense, I removed the interfaced and cleaned up a little

**Comment by clojj** [comment]
But I should learn more about what workes in multiplatform and what not, I guess

**Comment by sksamuel** [comment]
👍🏼

**Comment by clojj** [comment]
@sksamuel 
Hi, what is bothering me is that BookInput needs to be inside the domain model, but most of the time it is actually also a DTO/Json model from the outer web layer.. architecturally speaking.

On the other hand, any parser needs some input onbjects, so BookInput could also be seen as part of the domains/parsers API.

whar do you think?

**Comment by sksamuel** [comment]
Would you put validation inside your domain model ?
Why not a separate validation model ? After all the domain doesn't care about how you get there.

**Comment by clojj** [comment]
> Would you put validation inside your domain model ? Why not a separate validation model ? After all the domain doesn't care about how you get there. Isn't that the whole point of parsing not validation. That here is my domain model that I know is strict, and the values good. Any however you provide that to me is up to you, but I don't need to worry it's not in the right state.

yes, parsing happens outside domain, you're right
this is what it should look like I guess (will PR later)
image

**Comment by clojj** [comment]
> Would you put validation inside your domain model ?
> 
> Why not a separate validation model ? After all the domain doesn't care about how you get there. Isn't that the whole point of parsing not validation. That here is my domain model that I know is strict, and the values good. Any however you provide that to me is up to you, but I don't need to worry it's not in the right state.

From a different angle.. only the domain knows, how it is parsed correctly and how it's objects are constructed, I would say.

**Comment by sksamuel** [comment]
Yeah I guess that is true.

**Comment by sksamuel** [comment]
Maybe the domain should define a general purpose input format in addition
to the highly structured parsed format.

**Pull request merged**
